# -*- coding: utf-8 -*-
"""11365.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VMUCmOH05na33mkzWY0dJkRxuEJnac_0
"""

while True:
    sentence = input()
    
    if sentence == 'END':
        break
    else:
        print(sentence[::-1])

