# -*- coding: utf-8 -*-
"""회문은 회문아니야!!.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u_gA37r9ttylHZRT7Vfkear7hLr9hj2F
"""

s = input()

if s == s[0] * len(s): # 같은 알파벳으로만 이루어짐
    print(-1)
elif s != s[::-1]: # 팰린드롬 X
    print(len(s))
else: # 팰린드롬
    print(len(s) - 1)